# Generated by Django 6.0.4 on 2026-04-20 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_due_date_task_date_task_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Žádné"),
                    ("daily", "Denně"),
                    ("weekly", "Týdně"),
                    ("monthly", "Měsíčně"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Vysoká"), (2, "Střední"), (3, "Nízká")], default=2
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tasks.tag"),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_priority",
                    models.IntegerField(
                        choices=[(1, "Vysoká"), (2, "Střední"), (3, "Nízká")], default=2
                    ),
                ),
                (
                    "default_recurrence",
                    models.CharField(
                        choices=[
                            ("none", "Žádné"),
                            ("daily", "Denně"),
                            ("weekly", "Týdně"),
                            ("monthly", "Měsíčně"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("show_completed_tasks", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
