# Generated by Django 6.0.4 on 2026-04-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Vysoká"), (2, "Střední"), (3, "Nízká")], default=2
            ),
        ),
    ]
